<?php

namespace coletilla\proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class user extends \user implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getAdministrator()
    {
        $this->__load();
        return parent::getAdministrator();
    }

    public function getAnswers()
    {
        $this->__load();
        return parent::getAnswers();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function setAdministrator($administrator)
    {
        $this->__load();
        return parent::setAdministrator($administrator);
    }

    public function getNick_name()
    {
        $this->__load();
        return parent::getNick_name();
    }

    public function setNick_name($nick_name)
    {
        $this->__load();
        return parent::setNick_name($nick_name);
    }

    public function getSecret()
    {
        $this->__load();
        return parent::getSecret();
    }

    public function setSecret($secret)
    {
        $this->__load();
        return parent::setSecret($secret);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nick_name', 'secret', 'email', 'administrator', 'answers');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}